-- 회원가입 DB 만들기

-- H2 Database SQL

-- 테이블 삭제
DROP TABLE IF EXISTS member CASCADE;

-- 테이블 생성 (H2 DB SQL 문법으로 작성)
CREATE TABLE member (
                        id bigint generated by default as identity,
                        user_id varchar(255),
                        user_pw varchar(255),
                        user_name varchar(255),
                        user_role varchar(255),
                        joindate date default CURRENT_TIMESTAMP()
);

-- ROW 추가
INSERT INTO member VALUES (1, 'hong', '1234', '홍길동', 'ROLE_USER', '2023-09-09');
INSERT INTO member VALUES (2, 'tom', '1234', '톰아저씨', 'ROLE_USER', '2023-09-09');
INSERT INTO member VALUES (3, 'admin', '1234', '관리자', 'ROLE_ADMIN', '2023-09-09');

-- 검색
SELECT * FROM member;

-- 커밋하기 (실제 물리적으로 파일에 쓰기)
commit;