
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: profile, email
          kakao:
            # rest-api key
            client-id:
            client-name: Kakao
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            # http://localhost:8080/login/oauth2/code/kakao
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
          naver:
            client-id:
            client-secret:
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}' # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
